# Generated by Django 4.2.9 on 2024-02-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Calendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=100)),
                ("event_date", models.DateField()),
                ("event_time", models.TimeField()),
                ("event_location", models.CharField(max_length=100)),
                ("event_description", models.TextField()),
                ("event_attendees", models.IntegerField()),
                ("event_host", models.CharField(max_length=100)),
                ("event_host_email", models.EmailField(max_length=254)),
                ("event_host_phone", models.CharField(max_length=10)),
                (
                    "event_image",
                    models.ImageField(blank=True, upload_to="event_images/"),
                ),
            ],
        ),
    ]
