# Generated by Django 4.2.9 on 2024-02-03 20:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hackhive", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calendar",
            options={"verbose_name": "Scheduling", "verbose_name_plural": "Scheduling"},
        ),
    ]
