# Generated by Django 4.2.9 on 2024-02-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hackhive", "0003_alter_calendar_options_alter_calendar_event_host_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Calendar",
        ),
    ]
