# Generated by Django 4.2.9 on 2024-02-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hackhive", "0004_calendarevent_delete_calendar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.PositiveIntegerField()),
                ("year", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="CalendarEvent",
        ),
        migrations.AddField(
            model_name="calendar",
            name="events",
            field=models.ManyToManyField(
                blank=True, related_name="calendar_events", to="hackhive.event"
            ),
        ),
    ]
