# Generated by Django 4.2.9 on 2024-02-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hackhive", "0005_calendar_event_delete_calendarevent_calendar_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendar",
            name="events",
            field=models.ManyToManyField(blank=True, to="hackhive.event"),
        ),
    ]
