# Generated by Django 4.2.9 on 2024-02-03 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hackhive", "0006_alter_calendar_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendar",
            name="day",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="calendar",
            name="default",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="calendar",
            name="month",
            field=models.PositiveIntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                    (11, 11),
                    (12, 12),
                ]
            ),
        ),
    ]
