# Generated by Django 4.2.9 on 2024-02-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hackhive", "0007_calendar_day_calendar_default_alter_calendar_month"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calendar",
            name="day",
        ),
        migrations.RemoveField(
            model_name="calendar",
            name="default",
        ),
        migrations.RemoveField(
            model_name="calendar",
            name="events",
        ),
        migrations.AddField(
            model_name="calendar",
            name="day_of_workout",
            field=models.PositiveIntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                    (11, 11),
                    (12, 12),
                    (13, 13),
                    (14, 14),
                    (15, 15),
                    (16, 16),
                    (17, 17),
                    (18, 18),
                    (19, 19),
                    (20, 20),
                    (21, 21),
                    (22, 22),
                    (23, 23),
                    (24, 24),
                    (25, 25),
                    (26, 26),
                    (27, 27),
                    (28, 28),
                    (29, 29),
                    (30, 30),
                    (31, 31),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="calendar",
            name="description",
            field=models.TextField(default="Put workouts here", max_length=280),
        ),
        migrations.AddField(
            model_name="calendar",
            name="title",
            field=models.CharField(default="Legs", max_length=100),
        ),
        migrations.DeleteModel(
            name="Event",
        ),
    ]
