# Generated by Django 4.2.9 on 2024-02-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hackhive", "0008_remove_calendar_day_remove_calendar_default_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendar",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
